The first macro inherited from \textsf{article} is the \emph{emphasis} macro, \texttt{\textbackslash emph}.

We also have description lists:
\begin{description}
	\item[First] item
	\item[Second] item
\end{description}

We have quotes:
\begin{quote}
	To be or not to be, that is the question.
\end{quote}

Quotations:
\begin{quotation}
	A quotation is the repetition of one expression as part of another one, particularly when the quoted expression is well-known or explicitly attributed by citation to its original source, and it is indicated by (punctuated with) quotation marks.

	A quotation can also refer to the repeated use of units of any other form of expression, especially parts of artistic works: elements of a painting, scenes from a movie or sections from a musical composition.
\end{quotation}

Also, poetry:
\begin{verse}
Haikus are easy, \\
but sometimes they don't make sense. \\
Refrigerator.
\end{verse}
