name: Continuous integration
on:
  push:
    branches: [master]
  workflow_call:
permissions:
  contents: read
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: zauguin/install-texlive@v4
        with:
          texlive_version: 2026
          packages: >-
            scheme-basic
            collection-latexrecommended
            biber
            biblatex
            csquotes
            datatool
            everyhook
            fontaxes
            glossaries
            ly1
            marginnote
            mfirstuc
            minted
            mweights
            needspace
            opensans
            paratype
            sourcecodepro
            svn-prov
            xfor
            xindy
            xstring
            ydoc
            skdoc
            arev
            babel-german
            babel-swedish
            blindtext
            cleveref
            fixmath
            grid
            isodate
            isomath
            kpfonts
            siunitx
      - run: make dist
      - run: make test
      - uses: actions/upload-artifact@v7
        with:
          name: manual
          path: skrapport.pdf
      - uses: actions/upload-artifact@v7
        with:
          name: bundle
          path: skrapport.tar.gz
